name: coffeetakeaway
description: A new Flutter project.


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  flutter_spinkit: ^5.1.0
  flutter_svg: ^1.0.3
  font_awesome_flutter: ^9.2.0
  google_fonts: ^2.3.1
  shared_preferences: ^2.0.7
  json_annotation: ^4.0.0
  flutter_slidable: ^1.2.0
  http: ^0.13.0
  provider: ^6.0.2
  logging: ^1.0.1
  equatable: ^2.0.3
  cupertino_icons: ^1.0.2
  intl: ^0.17.0
  uuid: ^3.0.4
  smooth_page_indicator: ^1.0.0+2
  webview_flutter: ^2.0.13
  
  
  firebase_core: ^1.10.0  
  #firebase_analytics: ^8.3.4
  firebase_auth: ^3.2.0
  google_sign_in: ^5.0.1
  cloud_firestore: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.1
  json_serializable: ^4.1.4

 
  flutter_lints: ^1.0.0
 
flutter:

 
  uses-material-design: true


